FREQUENCIES
VARIABLES=attdrug phyheal menheal
/FORMAT=NOTABLE /*取消頻率表的顯示*/
/STATISTICS=STDDEV VARIANCE MINIMUM MAXIMUM MEAN SKEWNESS SESKEW KURTOSIS SEKURT /*選擇顯示的統計特征*/
/HISTOGRAM NORMAL /*直方圖添加正態曲線*/
/ORDER=ANALYSIS /*按輸出類型進行排序*/
