/*基於Tukey校正後的正交比較和成對比較.

/SPSS GLM*.
UNIANOVA
    POST BY TREATMNT WITH PRE
    /METHOD = SSTYPE(3)
    /INTERCEPT = INCLUDE
    /CRITERIA = ALPHA(.05)
    /LMATRIX “LINEAR” TREATMNT 1 0 −1
    /LMATRIX “QUADRATIC” TREATMNT 1 −2 1
    /DESIGN = PRE TREATMNT.

/*SPSS MANOVA.
MANOVA
    POST BY TREATMNT(1,3) WITH PRE
    /METHOD = UNIQUE
    /PARTITION (TREATMNT)
    /CONTRAST(TREATMNT)=SPECIAL(1 1 1, 1 0 -1, 1 -2 1)
    /ANALYSIS POST
    /DESIGN = PRE TREATMNT(1) TREATMNT(2).
